import Link from "next/link";

export const metadata = {
    title: "Tienda Page",
    description: "Generated by Next.js",
  };

export default function TiendaLayout({ children }) {
  return (
    <>
      <nav>
        <h1>Seccion Tienda</h1>

        <ul>
          <li>
            <Link href="/tienda/categorias">Categorias</Link>
          </li>
        </ul>
      </nav>
      {children}
    </>
  );
}
